include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - avoid_empty_else
    - await_only_futures
    - camel_case_extensions
    - prefer_single_quotes
    - annotate_overrides
    - avoid_print
# #     # camel_case_types: true
# #     # avoid_classes_with_only_static_members: false
# #     # comment_references: true
# #     # lines_longer_than_80_chars: false
# #     # prefer_single_quotes: true
# #     # sort_constructors_first: false
# #     # # avoid_classes_with_only_static_members: false
# #     # # argument_type_not_assignable: false
# #     # # comment_references: true
# #     # # lines_longer_than_80_chars: true
# #     # # prefer_single_quotes: true
# #     # # prefer_double_quotes: false
# #     # # sort_constructors_first: false
  
    
    