include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - avoid_empty_else
    - await_only_futures
    - camel_case_extensions
    - prefer_single_quotes
    
    - annotate_overrides
    - avoid_print
    - avoid_function_literals_in_foreach_calls
    # - avoid_renaming_method_parameters

# #     # camel_case_types: true
  
    
    