include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    avoid_empty_else: true
    await_only_futures: true
    camel_case_extensions: true
    prefer_single_quotes: true
    
    annotate_overrides: true
    avoid_print: true
    avoid_function_literals_in_foreach_calls: false
    # - avoid_renaming_method_parameters

# #     # camel_case_types: true
  
    
    