name: vet_app
description: Recibe reservas las 24 horas e incrementa los ingresos de tu veterinaria.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animate_do: ^2.0.0
  animated_text_kit: ^4.0.0
  cached_network_image: ^3.0.0
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.0.0
  date_time_picker: ^2.0.0
  day_night_time_picker: ^1.0.2
  easy_mask: ^2.0.1
  easy_rich_text: ^0.5.4
  email_validator: ^2.0.1
  file_picker: ^4.0.0
  # firebase_core: ^1.4.0
  # firebase_messaging: ^10.0.4
  fl_chart: ^0.36.0
  fluro: ^2.0.3
  flutter_blurhash: ^0.6.0
  flutter_cache_manager: ^3.1.2
  flutter_conditional_rendering: ^2.0.0
  flutter_dotenv: ^5.0.0
  flutter_linear_datepicker: ^1.1.2
  flutter_masked_text2: ^0.9.1
  flutter_sparkline: ^0.1.0
  flutter_typeahead: ^3.1.1
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.2
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
  http: ^0.13.3
  image_picker: ^0.7.3
  intl: ^0.17.0
  line_icons: ^2.0.1
  lottie: ^1.0.1
  octo_image: ^1.0.0+1
  percent_indicator: ^3.0.1
  rxdart: ^0.27.1
  scrollable_positioned_list: ^0.1.10
  select_dialog: ^2.0.0
  supabase: ^0.0.1-dev.17
  top_snackbar_flutter: ^1.0.0
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0
  whatsapp_unilink: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: null
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/proypet-partner.png"
  adaptive_icon_background: "assets/images/proypet-partner.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.dev
    - assets/map_style.txt
    - assets/images/
    - assets/images/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconProypet
      fonts:
        - asset: assets/fonts/IconProypet.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
