final jsonProximaCita = {
  'consultation': [
    'Chequeo preventivo',
    'Cirugía',
    'Consulta',
    'Exámenes',
    'Tratamiento',
  ],
  'deworming': [
    'Antipulgas',
    'Desparasitación',
    'Desparasitación externa',
    'Desparasitación interna',
  ],
  'grooming': [
    'Baño',
    'Baño medicado',
    'Baño y corte',
    'Limpieza dental',
    'Limpieza de glándulas',
  ],
  'vaccination': [
    'Vacuna antirrábica',
    'Vacuna distemper',
    'Vacuna leptospira',
    'Vacuna leucemia',
    'Vacuna parvovirus',
    'Vacuna refuerzo anual',
    'Vacuna tos de las perreras',
    'Vacuna triple',
    'Vacuna cuádruple',
    'Vacuna quíntuple',
    'Vacuna séxtuple',
  ],
};
